services:
  backend:
    build: .
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always